services:
  - type: web
    name: natursur-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate  
    startCommand: "gunicorn natursur.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: natursur.settings
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY
        sync: false  
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: natursur-db
          property: connectionString

  - type: worker
    name: natursur-tasks
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      python manage.py seed &&
      python manage.py update_products
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: natursur.settings
      - key: API_KEY
        sync: false

databases:
  - name: natursur-db
    plan: free
