services:
  - type: web
    name: natursur-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn natursur.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: natursur.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: API_KEY
        sync: false
